### ISSUE TITLE
README is inadequate

### ISSUE THREAD

**Issue by robo-jones** [jody/helloCS3250#6]
As a perspective contributor,
I want to learn the following from the README
- the intent of the project,
- how to build the product, and
- how to verify the correctness of the source code (run tests and code convention checks)

so that I can efficiently get started contributing to the project.

**Acceptance Criteria:**
- The README contains a description of the purpose of the project
- The README identifies dependencies, including runtime environments, development tools, and libraries not included in the repository, as well as information on how to obtain and install such dependencies
- The README contains instructions on how to build and run the product
- The README contains instructions for running the test suite and viewing results
- The README contains instructions for running the style checker and viewing the results

**Comment by jody** [comment]
This provides a useful perspective.  It is not yet an _effective_ issue because it doesn't specify the means to know whether the concern has been satisfactorily resolved.  That is, it lacks sufficient _acceptance criteria_.

Consider rewriting this in the form of a User Story with a rationale and acceptance critera.  (See course resources about User Stories and the textbook, _Software Development, Design and Coding_.)

**Comment by robo-jones** [comment]
I have rewritten the issue as requested.

**Comment by jody** [comment]
I've slightly modified the wording and added an "epic" label to indicate that this issue is large enough to warrant its decomposition into a collection of smaller issues.
